apiVersion: batch/v1
kind: CronJob
metadata:
  name: countdown
spec:
  schedule: "*/1 * * * *"  
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: hello
        image: busybox
        command:
         - "bin/bash"
         - "-c"
         - date; echo Hello from the Kubernetes cluster
        restartPolicy: OnFailure
