apiVersion: apps/v1
kind: Deployment
metadata:
  name: webby
  labels:
    app: webby
spec:
  selector:
    matchLabels:
      app: webby
  replicas: 2
  template:
    metadata:
      labels:
        app: webby
    spec:
      containers:
      - name: 5114-amin-webby
        image: reg.alta3.com/5114-amin-webby
        ports: 
        - containerPort: 8888
