apiVersion: v1
kind: Pod
metadata:
  name: webservice01
spec:
  containers:
  - name: 5114-amin-webby
    image: reg.alta3.com/5114-amin-webby
    ports:
    - name: web
      containerPort: 8888
      protocol: TCP
